Repository NewCentury99/Pet-Management, pull requests merged in 2021-08, with the labels that each got.

#56 [Hotfix/login-without-token-when-first-login] 첫 로그인 시 토큰을 저장하지 않는 문제
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/signIn/SignInFragment.kt
Labels: bug

#57 Fixed authenication exception in recovery API
  server/src/main/java/com/sju18/petmanagement/global/security/WebSecurityConfig.java
Labels: bug

#60 [hotfix/entity-naming-change] PetSchedule 엔티티의 컬럼명 변경
  server/src/main/java/com/sju18/petmanagement/domain/pet/application/PetScheduleService.java
  server/src/main/java/com/sju18/petmanagement/domain/pet/dao/PetSchedule.java
  server/src/main/java/com/sju18/petmanagement/domain/pet/dto/UpdatePetScheduleReqDto.java
Labels: bug, enhancement

#78 [feature/client-create-delete-follow] Client 팔로우 Create/Delete API 구현
  client/android/app/src/main/AndroidManifest.xml
  client/android/app/src/main/java/com/sju18001/petmanagement/MainActivity.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/restapi/ServerApi.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/restapi/dto/AccountDto.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/restapi/dto/FollowDto.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/createUpdatePost/CreateUpdatePostFragment.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/createUpdatePost/HashtagListAdapter.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/followerFollowing/FollowerAdapter.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/followerFollowing/FollowerFollowingActivity.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/followerFollowing/FollowerFollowingFragment.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/followerFollowing/FollowerFollowingListItem.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/followerFollowing/FollowerFollowingViewModel.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/followerFollowing/FollowerFragment.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/followerFollowing/FollowingFragment.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/followerFollowing/SearchActivity.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/community/followerFollowing/SearchViewModel.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/login/LoginFragment.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/login/createAccount/CreateAccountFragment.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/login/createAccount/CreateAccountUserInfoFragment.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/myPage/MyPageFragment.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/myPet/petManager/CreateUpdatePetFragment.kt
  client/android/app/src/main/java/com/sju18001/petmanagement/ui/myPet/petManager/PetProfileFragment.kt
  client/android/app/src/main/res/drawable/ic_baseline_search_24.xml
  client/android/app/src/main/res/layout/activity_follower_following.xml
  client/android/app/src/main/res/layout/activity_search.xml
  client/android/app/src/main/res/layout/follower_following_list_item.xml
  client/android/app/src/main/res/layout/fragment_create_update_post.xml
  client/android/app/src/main/res/layout/fragment_follower.xml
  client/android/app/src/main/res/layout/fragment_follower_following.xml
  client/android/app/src/main/res/layout/fragment_following.xml
  client/android/app/src/main/res/menu/follower_following_menu.xml
  client/android/app/src/main/res/values/strings.xml
  server/src/main/java/com/sju18/PetManagement/domain/account/dto/FetchAccountPhotoReqDto.java
  server/src/main/java/com/sju18/petmanagement/domain/account/api/AccountController.java
  server/src/main/java/com/sju18/petmanagement/domain/account/application/AccountService.java
  server/src/main/java/com/sju18/petmanagement/domain/account/dao/AccountRepository.java
  server/src/main/java/com/sju18/petmanagement/domain/account/dto/FetchAccountReqDto.java
  server/src/main/resources/static/messages/account/error_en.properties
Labels: enhancement
